name: CI-post-merge
on:
  push:
    branches:
    - main

jobs:

  re-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.23
    - name: Re-test
      run: make test

  update-tag:
    runs-on: ubuntu-latest
    needs:
    - re-test
    outputs:
      new_version: ${{ steps.tag_version.outputs.new_version }}
    steps:
    - uses: actions/checkout@v4
    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        default_bump: minor
